name: Run Karate Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-karate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Set Environment Variable for Karate
        run: echo "FAKERESTAPI=https://fakerestapi.azurewebsites.net/" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: echo "FAKERESTAPI=$FAKERESTAPI"

      - name: Run Karate tests
        run: mvn test -Dtest=FakeRESTApi.WebV1Runner -DFAKERESTAPI=$FAKERESTAPI
