name: Run Karate Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Karate Tests
        env:
          FAKERESTAPI: "https://fakerestapi.azurewebsites.net/"  # ✅ Passing Base URL as Env Variable
        run: mvn test

      - name: Upload Karate Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: target/surefire-reports
